import { JobOfferPage } from 'components/pages/jobOffersPage'
import type { NextPage } from 'next'
import Head from 'next/head'

const JobOfferRoute: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <JobOfferPage />
  </div>
)

export default JobOfferRoute
