import { JobOffersPage } from 'components/pages/jobOffersPage/jobOffersPage'
import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

const JobOffersRoute: NextPage = () => {
  const { data: session } = useSession()

  if (session) {
    return (
      <div>
        Signed in as {JSON.stringify(session)} <br />
      </div>
    )
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobOffersPage />
    </div>
  )
}

export default JobOffersRoute
