import axios from 'axios'
import { Heading } from 'components/common/heading'
import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useQuery } from 'react-query'

const JobOffersRoute: NextPage = () => {
  const { data: session } = useSession()

  useQuery({
    queryFn: () => axios.get('/api/offers'),
    onSuccess: (res) => {
      console.log(res)
    },
  })

  if (session) {
    return (
      <div>
        Signed in as {JSON.stringify(session)} <br />
      </div>
    )
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Heading tag="h1" size="base">
          List offert pracy
        </Heading>
      </div>
    </div>
  )
}

export default JobOffersRoute
